# Constantes del Toolbar - Lista maestra de todos los botones
# Versión: 1.0.1

TOOLBAR_MASTER_LAYOUT = [
    # Primera fila - Navegación básica
    "up",
    "root",
    "home",
    "refresh",
    "search",
    "separator",
    # Selección
    "select_all",
    "invert_selection",
    "deselect_all",
    "folders_only",
    "separator",
    # Operaciones de archivos
    "new_folder",
    "copy_path",
    "goto",
    "duplicate",
    "separator",
    # Herramientas de sistema
    "terminal",
    "powershell",
    "separator",
    # Paneles y utilidades
    "swap",
    "equal",
    "equal_reverse",
    "explorer",
    "separator",
    # Vista y navegación
    "view_mode",
    "recent_paths",
    "bookmarks",
    "apps",
    "plugins",
    # Spacer empuja lo siguiente a la derecha
    "spacer",
    # Botones alineados a la derecha (configuración e info)
    "settings",
    "help",
]

TOOLBAR_DISPLAY_NAMES = {
    "up": "🔼 Subir un nivel",
    "root": "📁 Raíz del sistema",
    "home": "🏠 Directorio personal",
    "refresh": "🔄 Refrescar",
    "search": "🔍 Buscar",
    "separator": "--- Separador ---",
    "select_all": "☑ Seleccionar todo",
    "invert_selection": "↔ Invertir selección",
    "deselect_all": "☐ Deseleccionar todo",
    "folders_only": "📂 Solo carpetas",
    "new_folder": "📁 Nueva carpeta",
    "copy_path": "📋 Copiar ruta",
    "goto": "🎯 Ir a ruta",
    "duplicate": "📄 Duplicar",
    "terminal": "💻 Terminal aquí",
    "powershell": "📟 PowerShell aquí",
    "swap": "⇄ Intercambiar paneles",
    "equal": "➡ Igualar paneles",
    "equal_reverse": "⬅ Igualar activo a inactivo",
    "explorer": "📂 Abrir en Explorer",
    "view_mode": "👁 Modo de vista",
    "recent_paths": "🕐 Rutas recientes",
    "bookmarks": "🔖 Marcadores",
    "apps": "🚀 Aplicaciones",
    "plugins": "🧩 Plugins",
    "spacer": "--- Espaciador ---",
    "settings": "⚙ Configuración",
    "help": "❓ Ajuda rapida",
}

TOOLBAR_DEFAULT_TOOLTIPS = {
    "up": "Subir al directorio superior (Backspace)",
    "root": "Ir a la raíz del sistema",
    "home": "Ir a la carpeta personal del usuario",
    "refresh": "Actualizar la lista de archivos (F5)",
    "search": "Buscar archivos y carpetas (F3)",
    "select_all": "Seleccionar todos los elementos (Ctrl+A)",
    "invert_selection": "Invertir la selección actual (Ctrl+I)",
    "deselect_all": "Deseleccionar todo (Ctrl+Shift+A)",
    "folders_only": "Alternar vista: Solo carpetas o todo (Ctrl+Shift+F)",
    "new_folder": "Crear una nueva carpeta (F7)",
    "copy_path": "Copiar la ruta actual al portapapeles",
    "goto": "Ir a una ruta específica (Ctrl+G)",
    "duplicate": "Duplicar archivos/carpetas seleccionados en el mismo directorio (Ctrl+D)",
    "terminal": "Abrir CMD en la ruta actual",
    "powershell": "Abrir PowerShell en la ruta actual",
    "swap": "Intercambiar las rutas de ambos paneles (Ctrl+U)",
    "equal": "Igualar el panel inactivo al activo",
    "equal_reverse": "Igualar el panel activo al inactivo (Ctrl+Alt+Left)",
    "explorer": "Abrir la ruta actual en el Explorador de Windows",
    "view_mode": "Cambiar el modo de visualización",
    "recent_paths": "Ver historial de carpetas visitadas",
    "bookmarks": "Gestionar y acceder a marcadores favoritos",
    "apps": "Ejecutar aplicaciones configuradas",
    "plugins": "Acceder a herramientas y plugins adicionales",
    "settings": "Configurar opciones del programa",
    "help": "Ajuda rapida - dreceres i funcions (F1)",
}
